name: .NET Linux Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        CONFIGURATION: [Debug, Release]

    # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    env:
      # set consol column widht so a certain [TextFormatting]-test might not fail
      COLUMNS: 120

      # Replace with your solution name, i.e. MyWpfApp.sln.
      SOLUTION_NAME: "./ConsoleProgressBar/ConsoleProgressBar.sln"

      # Deactivated Test_Project_Path: your-test-project-path                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      # Deactivated Wap_Project_Directory: your-wap-project-directory-name    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      # Deactivated Wap_Project_Path: your-wap-project-path                   # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Use latest LTS, adjust if your project uses a different version

    # DEBUG
    #- name: List files
    #  run: ls -R

    - name: Restore dependencies
      run: dotnet restore $SOLUTION_NAME
      #working-directory: ./ConsoleProgressBar

    - name: Build
      run: dotnet build $SOLUTION_NAME --no-restore
      #working-directory: ./ConsoleProgressBar

    - name: Test
      run: dotnet test $SOLUTION_NAME --no-build --verbosity normal
      #working-directory: ./ConsoleProgressBar

  pack_and_publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Use latest LTS, adjust if your project uses a different version

    #- name: Restore dependencies
    #  run: dotnet restore $SOLUTION_NAME

    - name: Pack
      run: dotnet pack $SOLUTION_NAME --configuration Release --output ./artifacts

    - name: Get package version
      id: get_version
      run: |
        PACKAGE_VERSION=$(ls ./artifacts | grep .nupkg | sed 's/.*\.//' | sed 's/\.nupkg$//')
        echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

    - name: Publish
      run: dotnet nuget push ./artifacts/*.nupkg --source github --api-key ${{ secrets.NUGET_API_KEY }}