name: .NET Linux Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        CONFIGURATION: [Debug, Release]

    # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    env:
      # set consol column widht so a certain [TextFormatting]-test might not fail
      COLUMNS: 120

      # Replace with your solution name, i.e. MyWpfApp.sln.
      SOLUTION_NAME: "./ConsoleProgressBar/ConsoleProgressBar.sln"

      # Deactivated Test_Project_Path: your-test-project-path                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      # Deactivated Wap_Project_Directory: your-wap-project-directory-name    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      # Deactivated Wap_Project_Path: your-wap-project-path                   # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.

    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Use latest LTS, adjust if your project uses a different version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build $env:SOLUTION_NAME --configuration ${{ matrix.configuration }} --no-restore

    - name: Execute unit tests
      run: dotnet test $env:SOLUTION_NAME --no-build --verbosity normal
